<?php 
	$linkStart = $this->currentUrl . '/page/' . $this->first;
	$linkPrevious = "#";
	if (isset($this->previous)) {
		$linkPrevious = $this->currentUrl . '/page/' . $this->previous;
	}
	$linkNext = "#";
	if (isset($this->next)) {
		$linkNext = $this->currentUrl . '/page/' . $this->next;
	}
	$linkEnd = $this->currentUrl . '/page/' . $this->last;
	$strPage = '';
	foreach ($this->pagesInRange as $key=>$value) {
		if ($this->current == $key) {
			//----- khong co link
			$strPage .= '<li class="active"><a>' . $key .'</a></li>';	
		} else {
			//----- co link
			$linkPage = $this->currentUrl . '/page/' .$key;
			$strPage .= '<li><a href="' .$linkPage . '">' .$key .'</a></li>';
		}
	}
	
	$page = 'Page ' .$this->current .' of ' .$this->last;
?>

<li><a href="<?php echo $linkStart;?>" title="Start">&laquo;</a></li>

<?php echo $strPage;?>
<li><a href="<?php echo $linkEnd;?>" title="End">&raquo;</a></li>