<div class="row">
	<div class="col-md-8 col-md-offset-2 introduce">
	<?php
		$thisPage = $this->Item;
		if (!empty($thisPage)) {
			$thisPage = $this->cmsReplaceString($thisPage);
			$page_title = $thisPage['page_title'];
			$page_content = $thisPage['page_content'];
			$cover_image = FILES_URL . '/pages/cover-images/medium/' . $thisPage['cover_image'];
		}
	?>
		<h3><?php echo $page_title; ?></h3>
		<hr/>
		<div class="row">
			<div class="col-md-9">
				<img src="<?php echo $cover_image; ?>" alt="cnt gioi thieu cong ty" class="img-thumbnail introduce-image"/>
				<div class="company-introduce">
					<p><?php echo $page_content; ?></p>
				</div>
			</div>
			
			<?php echo $this->blkAboutUs(); ?>
			
		</div>
	</div>
</div>