
<div class="row">
	<div class="col-lg-12">
		<div id="toolbar-box">
			<div class="t">
				<div class="t">
					<div class="t"></div>
				</div>
			</div>
			
			<div class="m">
				
				<h3 class="page-header"><?php echo $this->Title; ?></h3>
		                                
				<div class="clr"></div>
			</div>
			<div class="b">
				<div class="b">
					<div class="b"></div>
				</div>
			</div>
		</div>
	</div>
</div>
	
<form name="appForm" method="post" action="" enctype="multipart/form-data">
	
	<div id="row" class="row page-header">
	<div class="col-lg-2">
		<strong>Import File Excel</strong>
	</div>
	<div class="col-lg-4">
		<input type="FILE" name="excel">
	</div>
	<div class="col-lg-6">
		<input type="submit" name="submit" value="Submit">
	</div>

</div>
</form>

<?php 
if($this->mes!=''){ 

echo '<div class="alert alert-danger">'.$this->mes.'</div>';}

?>


